spring:
  application:
    name: Spring Cloud Config Server
  cloud:
    config:
      server:
        git:
          uri: git@github.com:KAnggara/scc
          search-paths:
            - dev
            - prd
