name: Build Image and Push to GHCR

on:
  push:
    branches: ["main"]

jobs:
  mvn-build:
    runs-on: ubuntu-24.04
    name: Maven Build
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: KAnggara/DevOps/mavenbuild@HEAD
        with:
          java-version: "17"
          distribution: "temurin"
          application-properties: ${{ secrets.APPLICATION_PROPERTIES }}

  docker-build:
    runs-on: ubuntu-24.04
    needs: mvn-build
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    name: Build and Push Image
    steps:
      - uses: actions/download-artifact@v4.1.8
        with:
          name: ${{ github.event.repository.name }}
          path: target/
      - name: Build Docker Image then Push
        uses: KAnggara/DevOps/dockerbuild@HEAD
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
