name: Build Image and Push to GHCR

on:
  push:
    branches: ["main"]

jobs:
  build-image:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    name: Build and Push Image
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: KAnggara/DevOps/mavenbuild@HEAD
        with:
          java-version: "17"
          distribution: "temurin"
          application-properties: ${{ secrets.APPLICATION_PROPERTIES }}
      - name: Build
        uses: KAnggara/DevOps/dockerbuild@HEAD
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
